### ISSUE TITLE
Polish and refactor the code

### ISSUE THREAD

**Issue by podliashanyk** [Uninett/Howitz#29]
### Tasks:

- [x] handle all explicit exceptions (see comment _Originally posted by @hmpf in https://github.com/Uninett/Howitz/pull/26#pullrequestreview-1701057398_)
- [ ] protect routes that are there solely for HTMX. Per now user can access all routes even those that are "util" routes meant to be used just for the GUI bit
- [ ] add dependencies in a way that suits production (no cdn stuff)
- [ ] clean up/simplify tailwind 
- [ ] clean up/refactor HTML code
- [x] extend/update documentation
- [ ] ...
